@baseUrl = http://localhost:3333

###
POST {{baseUrl}}/events
Content-Type: application/json

{
  "title": "Unit Summit",
  "details": "Um evento para quem é apaixonado por programação",
  "maximumAttendees": 120
}

###
GET {{baseUrl}}/events/0690fdeb-d32e-43c6-be6a-eb7e8fd53f4d

###
POST {{baseUrl}}/events/0690fdeb-d32e-43c6-be6a-eb7e8fd53f4d/attendees
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com"
}

###
POST {{baseUrl}}/events/0690fdeb-d32e-43c6-be6a-eb7e8fd53f4d/attendees
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@example.com"
}

###
GET {{baseUrl}}/attendees/1/badge

###
GET {{baseUrl}}/events/0690fdeb-d32e-43c6-be6a-eb7e8fd53f4d/attendees


###
GET {{baseUrl}}/events/0690fdeb-d32e-43c6-be6a-eb7e8fd53f4d/attendees?query=john
